version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        - DEV=true
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - jwt-auth

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - jwt-auth

  postgres-db:
    image: postgres:12.0-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - jwt-auth

  nginx:
    restart: always
    depends_on:
      - api
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - jwt-auth

networks:
  jwt-auth:
    driver: bridge

volumes:
  dev-db-data:
  static_volume:
  media_volume:
